import type { Lang } from '../copy';
import built from '../generated/diagrams.json';

type Key = keyof typeof built;

type Props = {
  /** Which entry of `src/diagrams.sources.json` to show. */
  name: Key;
  /**
   * Which language to draw it in.
   *
   * The picture carries three things that have a language — the names on the boxes, the
   * legend, and the diagnostics quoted beside it — so this is not decoration. Every
   * example is compiled once per language at build time.
   */
  lang: Lang;
  /** Filename shown as a mono label above the code — a label, not fake window chrome. */
  filename: string;
  /**
   * `row` puts source and output side by side; `stack` puts them in one column.
   *
   * The hero needs `stack`: it is already a two-column layout, and nesting another pair
   * inside its right half squeezes both to a quarter of the page.
   */
  layout?: 'row' | 'stack';
};

/** Minimal highlighter for the token classes the stylesheet defines. */
function highlight(source: string): string {
  return source
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/(#[^\n]*)/g, '<span class="c">$1</span>')
    .replace(/("[^"\n]*")/g, '<span class="s">$1</span>')
    .replace(
      /\b(diagram|device|adapter|group|model|signal|compat|use|in|out|io|as|from|over|via|gap)\b/g,
      '<span class="k">$1</span>',
    )
    .replace(/(-&gt;|&lt;-&gt;|--)/g, '<span class="n">$1</span>');
}

/**
 * A `.khm` source and the diagram it actually produces.
 *
 * The SVG was generated by the published package at build time — not screenshotted, not
 * redrawn. `scripts/build-diagrams.mjs` fails the build if any of these examples produces
 * a diagnostic, so the page cannot quietly start showing faulty wiring.
 *
 * Both `dangerouslySetInnerHTML` sites are safe because of where the content comes from:
 * every source is a literal in this repository, and the renderer escapes text and
 * validates colours before they reach an attribute. Point this at source someone else
 * supplied and it would need `sanitizeSvg` from `@love-rox/kumihimo-editor` first.
 */
export function Diagram({ name, filename, lang, layout = 'row' }: Props) {
  const entry = built[name][lang];

  return (
    <div className={layout === 'stack' ? 'play__stack' : 'play__row'}>
      <div className="slab">
        <div className="slab__label">
          <span className="mono">{filename}</span>
          {entry.diagnostics === 0 ? (
            <span className="chip chip--ok">clean</span>
          ) : (
            <span className="chip">{entry.diagnostics} diagnostic</span>
          )}
        </div>
        <pre className="code">
          <code dangerouslySetInnerHTML={{ __html: highlight(entry.source) }} />
        </pre>
      </div>
      <div className="slab">
        <span className="mono">output</span>
        <div className="preview" dangerouslySetInnerHTML={{ __html: entry.svg }} />
      </div>
    </div>
  );
}
