import type { Lang } from '../copy';
import built from '../generated/diagrams.json';

type Key = keyof typeof built;

type Props = {
  /** Which entry of `src/diagrams.sources.json` to show. */
  name: Key;
  /**
   * Which language to draw it in.
   *
   * The picture carries three things that have a language — the names on the boxes, the
   * legend, and the diagnostics quoted beside it — so this is not decoration. Every
   * example is compiled once per language at build time.
   */
  lang: Lang;
  /** Filename shown as a mono label above the code — a label, not fake window chrome. */
  filename: string;
  /**
   * `row` puts source and output side by side; `stack` puts them in one column.
   *
   * The hero needs `stack`: it is already a two-column layout, and nesting another pair
   * inside its right half squeezes both to a quarter of the page.
   */
  layout?: 'row' | 'stack';
};

/** Minimal highlighter for the token classes the stylesheet defines. */
export function highlight(source: string): string {
  const escaped = source.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');

  // One pass, and one pass only. As a chain of `.replace` calls this ate itself: comments
  // were wrapped first, and the string rule then found the `"c"` inside the `class="c"`
  // it had just written and wrapped *that*, so every commented line rendered with `"c">`
  // sitting in front of the comment. Alternation consumes each character once, which also
  // stops a keyword inside a quoted name from being coloured as a keyword.
  return escaped.replace(
    /(#[^\n]*)|("[^"\n]*")|\b(diagram|device|adapter|group|model|signal|compat|use|in|out|io|as|from|over|via|gap)\b|(-&gt;|&lt;-&gt;|--)/g,
    (_whole, comment?: string, text?: string, keyword?: string, arrow?: string) => {
      if (comment !== undefined) return `<span class="c">${comment}</span>`;
      if (text !== undefined) return `<span class="s">${text}</span>`;
      if (keyword !== undefined) return `<span class="k">${keyword}</span>`;
      return `<span class="n">${arrow}</span>`;
    },
  );
}

/**
 * A `.khm` source and the diagram it actually produces.
 *
 * The SVG was generated by the published package at build time — not screenshotted, not
 * redrawn. `scripts/build-diagrams.mjs` fails the build if any of these examples produces
 * a diagnostic, so the page cannot quietly start showing faulty wiring.
 *
 * Both `dangerouslySetInnerHTML` sites are safe because of where the content comes from:
 * every source is a literal in this repository, and the renderer escapes text and
 * validates colours before they reach an attribute. Point this at source someone else
 * supplied and it would need `sanitizeSvg` from `@love-rox/kumihimo-editor` first.
 */
export function Diagram({ name, filename, lang, layout = 'row' }: Props) {
  const entry = built[name][lang];

  return (
    <div className={layout === 'stack' ? 'play__stack' : 'play__row'}>
      <div className="slab">
        <div className="slab__label">
          <span className="mono">{filename}</span>
          {entry.diagnostics === 0 ? (
            <span className="chip chip--ok">clean</span>
          ) : (
            <span className="chip">{entry.diagnostics} diagnostic</span>
          )}
        </div>
        <pre className="code">
          <code dangerouslySetInnerHTML={{ __html: highlight(entry.source) }} />
        </pre>
      </div>
      <div className="slab">
        <span className="mono">output</span>
        <div className="preview" dangerouslySetInnerHTML={{ __html: entry.svg }} />
      </div>
    </div>
  );
}
